### PR TITLE
Vue router merge to Dev

### PR DESCRIPTION
**Pull request by IMBCIT**
This is a simple vue-router example that is going to be used as the base of our wiki page for the project. I am creating this PR now as I am working on the vuex portion and will be integrating and creating tasks into the Wiki portion of the project.

### CODE REVIEW

**Comment by hiyaryan** [comment]
Did you want to keep the About page? I was thinking you could have refactored it making it the Wiki page since it wasn't in our mockup.

**Comment by IMBCIT** [comment]
I was thinking of keeping it around to explain what we are doing and share other information but we can remove it if you'd like.

**Comment by hiyaryan** [comment]
We don't really need it. Probably better to get rid of it.

**Review by ezio-melotti — APPROVED** [review]

**Comment by ezio-melotti** [comment]
It's great to see that you added some unittest!  Currently the frontend doesn't have tests but eventually we do want to add them (we are working on adding tests to the backend right now).  Ideally any new piece of code should come with unit tests, so learning how unit tests work and getting the habit of adding them is definitely a good idea.

**Comment by IMBCIT** [comment]
I was going to be writing them as we continued this small repo but I believe that we are switching our focus to the main SIMOC front end branch for our Capstone so I just included what I had.

Pretty sure my initial tests were just place holders and wouldn't work but I am hoping to start integrating them when we write our code for the SIMOC front end additions.

**Pull request merged**
